import {
  defineProvider,
  STANDARD_EMBED_PLAYER_PARAMS,
  VIDCORE_PLAYER_PARAMS
} from "./providerDefinition.js";
import type { ProviderCatalogEntry } from "./providerTypes.js";

export const STREAM_PROVIDERS: ProviderCatalogEntry[] = [
  defineProvider({
    key: "111movies",
    name: "111movies",
    category: "other",
    idType: "both",
    website: "https://111movies.net",
    canBeScraped: true,
    referrerPolicy: "no-referrer",
    moviePath: (id) => `/movie/${id}`,
    tvPath: (id, season, episode) => `/tv/${id}/${season}/${episode}`
  }),
  defineProvider({
    key: "2embed",
    name: "2Embed",
    category: "other",
    idType: "imdb",
    website: "https://www.2embed.cc",
    animeIdType: "anilist",
    dubSupport: true,
    referrerPolicy: "no-referrer",
    moviePath: (id) => `/embed/${id}`,
    tvPath: (id, season, episode) => `/embed/${id}/${season}/${episode}`,
    animePath: (id, _season, episode, dub) =>
      `/embed/anime/${id}/${episode}${dub ? "?dub=true" : ""}`
  }),
  defineProvider({
    key: "cinesrc",
    name: "CineSrc",
    category: "other",
    idType: "tmdb",
    website: "https://cinesrc.st",
    canBeScraped: true,
    progress: { resumeParam: "time", controlApi: true },
    params: {
      seek: { type: "number" },
      autoplay: { type: "boolean", default: true },
      muted: { type: "boolean", default: false },
      color: { type: "hex" },
      controls: { type: "boolean", default: true },
      back: { type: "string" },
      autonext: { type: "boolean", default: false },
      autoskip: { type: "boolean", default: false },
      prioritize: { type: "boolean", default: false },
      lastserver: { type: "string" },
      t: { type: "time" },
      continueprompt: { type: "boolean", default: true },
      quality: { type: "string" },
      febbox: { type: "string" }
    },
    moviePath: (id) => `/embed/movie/${id}`,
    tvPath: (id, season, episode) => `/embed/tv/${id}?s=${season}&e=${episode}`
  }),
  defineProvider({
    key: "cinezo",
    name: "Cinezo",
    category: "other",
    idType: "tmdb",
    website: "https://player.cinezo.live",
    animeIdType: "anilist",
    dubSupport: true,
    progress: { resumeParam: "startAt" },
    params: {
      primarycolor: { type: "hex" },
      secondarycolor: { type: "hex" },
      iconcolor: { type: "hex" },
      autoplay: { type: "boolean", default: true },
      poster: { type: "boolean", default: true },
      chromecast: { type: "boolean", default: true },
      servericon: { type: "boolean", default: true },
      setting: { type: "boolean", default: true },
      pip: { type: "boolean", default: true },
      font: { type: "string" },
      fontcolor: { type: "hex" },
      fontsize: { type: "number" },
      opacity: { type: "number" },
      logourl: { type: "string" },
      server: { type: "string" },
      nextButton: { type: "boolean" },
      autoNext: { type: "boolean" },
      download: { type: "boolean" },
      episodes: { type: "boolean" }
    },
    moviePath: (id) => `/embed/movie/${id}`,
    tvPath: (id, season, episode) => `/embed/tv/${id}/${season}/${episode}`,
    animePath: (id, _season, episode, dub) =>
      `/embed/anime/${id}/${episode}${dub ? "?dub=true" : ""}`
  }),
  defineProvider({
    // for tvSeasonMappings.ts
    key: "direct",
    name: "Direct",
    category: "other",
    idType: "tmdb",
    website: "",
    moviePath: () => "",
    tvPath: () => ""
  }),
  defineProvider({
    key: "filmu",
    name: "Filmu",
    category: "primary_anime",
    idType: "both",
    website: "https://embed.filmu.in",
    animeIdType: "anilist",
    dubSupport: true,
    referrerPolicy: "no-referrer",
    moviePath: (id) => `/embed/movie/${id}`,
    tvPath: (id, season, episode) => `/embed/tv/${id}/${season}/${episode}`,
    animePath: (id, _season, episode, dub) =>
      `/embed/anime/${id}/${episode}${dub ? "?dub=true" : ""}`
  }),
  defineProvider({
    key: "megaplay",
    name: "MegaPlay",
    category: "primary_anime",
    idType: "tmdb",
    website: "https://megaplay.buzz",
    animeOnly: true,
    animeIdType: "anilist",
    dubSupport: true,
    progress: { resumeParam: "startAt" },
    canBeScraped: true,
    serverParam: "s",
    servers: [
      { id: "default", label: "Default" },
      { id: "bcdn", label: "BCDN", value: "bcdn" },
      { id: "tcdn", label: "TCDN", value: "tcdn" }
    ],
    moviePath: (id) => `/stream/ani/${id}/1/dub`,
    tvPath: (id, _season, episode) => `/stream/ani/${id}/${episode}/dub`,
    animePath: (id, _season, episode, dub) => `/stream/ani/${id}/${episode}/${dub ? "dub" : "sub"}`,
    malAnimePath: (id, _season, episode, dub) =>
      `/stream/mal/${id}/${episode}/${dub ? "dub" : "sub"}`
  }),
  defineProvider({
    key: "zokoanime",
    name: "ZokoAnime",
    category: "other",
    idType: "tmdb",
    website: "https://zokoanime.video",
    animeOnly: true,
    animeIdType: "anilist",
    dubSupport: true,
    progress: { resumeParam: "time" },
    params: {
      color: { type: "hex" },
      autoplay: { type: "boolean", default: true },
      muted: { type: "boolean", default: false },
      time: { type: "time" },
      resume: { type: "boolean", default: true },
      asi: { type: "boolean" },
      autonext: { type: "boolean", default: false }
    },
    moviePath: (id) => `/stream/ani/${id}/1/sub`,
    tvPath: (id, _season, episode) => `/stream/ani/${id}/${episode}/sub`,
    animePath: (id, _season, episode, dub) => `/stream/ani/${id}/${episode}/${dub ? "dub" : "sub"}`,
    malAnimePath: (id, _season, episode, dub) =>
      `/stream/mal/${id}/${episode}/${dub ? "dub" : "sub"}`
  }),
  defineProvider({
    key: "peachify",
    name: "Peachify",
    category: "primary",
    idType: "tmdb",
    website: "https://peachify.top",
    progress: { resumeParam: "startAt" },
    canBeScraped: true,
    referrerPolicy: "no-referrer",
    params: {
      server: { type: "string" },
      dub: { type: "string" },
      sub: { type: "string" },
      startAt: { type: "time" },
      autoNext: { type: "number", default: 1 },
      showNextBtn: { type: "boolean", default: true },
      autoPlay: { type: "boolean", default: true },
      pip: { type: "string" },
      cast: { type: "string" },
      fullscreen: { type: "string" },
      volume: { type: "string" },
      servers: { type: "string" },
      captions: { type: "string" },
      quality: { type: "string" }
    },
    moviePath: (id) => `/embed/movie/${id}`,
    tvPath: (id, season, episode) => `/embed/tv/${id}/${season}/${episode}`
  }),
  defineProvider({
    key: "tryembed",
    name: "TryEmbed",
    category: "primary_anime",
    idType: "tmdb",
    website: "https://tryembed.us.cc",
    animeIdType: "anilist",
    dubSupport: true,
    progress: { resumeParam: "startAt" },
    referrerPolicy: "no-referrer",
    params: {
      autoplay: { type: "boolean", default: true },
      autoSkip: { type: "boolean", default: false },
      autoNext: { type: "boolean", default: false },
      "lang-type": { type: "boolean", default: false },
      startAt: { type: "time" },
      opensubs: { type: "string" }
    },
    moviePath: (id) => `/embed/movie/${id}`,
    tvPath: (id, season, episode) => `/embed/tv/${id}/${season}/${episode}`,
    animePath: (id, _season, episode, dub) => `/embed/anime/${id}/${episode}/${dub ? "dub" : "sub"}`
  }),
  defineProvider({
    key: "vaplayer",
    name: "Vaplayer",
    category: "other",
    idType: "both",
    website: "https://vaplayer.ru",
    params: {
      primaryColor: { type: "hex" },
      color: { type: "hex" },
      title: { type: "string" },
      poster: { type: "string" },
      showTitle: { type: "boolean", default: true },
      autoplay: { type: "number", default: 0 },
      startAt: { type: "time" },
      resumeAt: { type: "time" },
      sub_url: { type: "string" },
      sub_file: { type: "string" },
      sub_label: { type: "string" },
      sub_lang: { type: "string" },
      sub_default: { type: "boolean", default: false },
      ds_lang: { type: "string" },
      lang: { type: "string" },
      controls: { type: "boolean", default: true },
      overlay: { type: "boolean", default: true },
      thumbnails: { type: "string" }
    },
    moviePath: (id) => `/embed/movie/${id}`,
    tvPath: (id, season, episode) => `/embed/tv/${id}/${season}/${episode}`
  }),
  defineProvider({
    key: "vidcore",
    name: "VidCore",
    category: "primary",
    idType: "both",
    website: "https://vidcore.io",
    progress: { controlApi: true },
    params: VIDCORE_PLAYER_PARAMS,
    moviePath: (id) => `/movie/${id}`,
    tvPath: (id, season, episode) => `/tv/${id}/${season}/${episode}`
  }),
  defineProvider({
    key: "videasy",
    name: "VidEasy",
    category: "other",
    idType: "tmdb",
    website: "https://player.videasy.net",
    animeIdType: "anilist",
    progress: { resumeParam: "progress" },
    referrerPolicy: "no-referrer",
    params: {
      color: { type: "hex" },
      progress: { type: "time" },
      nextEpisode: { type: "boolean", default: false },
      episodeSelector: { type: "boolean", default: false },
      autoplayNextEpisode: { type: "boolean", default: false },
      overlay: { type: "boolean", default: true }
    },
    moviePath: (id) => `/movie/${id}`,
    tvPath: (id, season, episode) => `/tv/${id}/${season}/${episode}`,
    animePath: (id, _season, episode) => `/anime/${id}/${episode}`
  }),
  defineProvider({
    key: "vidfast",
    name: "VidFast",
    category: "other",
    idType: "both",
    website: "https://vidfast.pro",
    origins: [
      "https://vidfast.pro",
      "https://vidfast.in",
      "https://vidfast.io",
      "https://vidfast.me",
      "https://vidfast.net",
      "https://vidfast.pm",
      "https://vidfast.vc",
      "https://vidfast.bz",
      "https://vidfast.xyz"
    ],
    progress: { resumeParam: "startAt", controlApi: true },
    referrerPolicy: "no-referrer",
    params: STANDARD_EMBED_PLAYER_PARAMS,
    moviePath: (id) => `/movie/${id}`,
    tvPath: (id, season, episode) => `/tv/${id}/${season}/${episode}`
  }),
  defineProvider({
    key: "vidlove",
    name: "VidLove",
    category: "other",
    idType: "tmdb",
    website: "https://player.vidlove.cc",
    progress: { controlApi: true },
    referrerPolicy: "no-referrer",
    params: {
      primarycolor: { type: "hex" },
      secondarycolor: { type: "hex" },
      iconcolor: { type: "hex" },
      autoplay: { type: "boolean" },
      poster: { type: "boolean" },
      chromecast: { type: "boolean" },
      servericon: { type: "boolean" },
      setting: { type: "boolean" },
      pip: { type: "boolean" },
      font: { type: "string" },
      fontcolor: { type: "hex" },
      fontsize: { type: "number" },
      opacity: { type: "number" },
      logourl: { type: "string" },
      server: { type: "string" }
    },
    moviePath: (id) => `/embed/movie/${id}`,
    tvPath: (id, season, episode) => `/embed/tv/${id}/${season}/${episode}`
  }),
  defineProvider({
    key: "vidlux",
    name: "VidLux",
    category: "other",
    idType: "tmdb",
    website: "https://vidlux.xyz",
    canBeScraped: true,
    params: {
      key: { type: "string" },
      color: { type: "hex" },
      logo: { type: "string" },
      autoplay: { type: "boolean", default: true },
      server: { type: "string", default: "star" },
      title: { type: "string" }
    },
    moviePath: (id) => `/embed/movie/${id}`,
    tvPath: (id, season, episode) => `/embed/tv/${id}/${season}/${episode}`
  }),
  defineProvider({
    key: "vidnest",
    name: "VidNest",
    category: "other",
    idType: "tmdb",
    website: "https://vidnest.fun",
    canBeScraped: true,
    animeIdType: "anilist",
    dubSupport: true,
    progress: { resumeParam: "progress" },
    referrerPolicy: "no-referrer",
    params: {
      startAt: { type: "time" },
      progress: { type: "time" },
      server: { type: "string" },
      servericon: { type: "string" },
      topcaption: { type: "string" },
      topsettings: { type: "string" },
      centerseekbackward: { type: "string" },
      centerplay: { type: "string" },
      centerseekforward: { type: "string" },
      timeslider: { type: "string" },
      mute: { type: "string" },
      volume: { type: "string" },
      timegroup: { type: "string" },
      bottomcaption: { type: "string" },
      bottomsettings: { type: "string" },
      pip: { type: "string" },
      cast: { type: "string" },
      fullscreen: { type: "string" },
      prevepisode: { type: "string" },
      nextepisode: { type: "string" }
    },
    moviePath: (id) => `/movie/${id}`,
    tvPath: (id, season, episode) => `/tv/${id}/${season}/${episode}`,
    animePath: (id, _season, episode, dub) => `/anime/${id}/${episode}${dub ? "/dub" : "/sub"}`
  }),
  defineProvider({
    key: "vidrock",
    name: "VidRock",
    category: "other",
    idType: "both",
    website: "https://vidrock.ru",
    animeIdType: "anilist",
    dubSupport: true,
    referrerPolicy: "strict-origin-when-cross-origin",
    params: {
      autoplay: { type: "boolean", default: true },
      autonext: { type: "boolean", default: false },
      theme: { type: "hex" },
      download: { type: "boolean", default: true },
      nextbutton: { type: "boolean", default: true },
      episodeselector: { type: "boolean", default: true },
      lang: { type: "string" }
    },
    moviePath: (id) => `/embed/movie/${id}`,
    tvPath: (id, season, episode) => `/embed/tv/${id}/${season}/${episode}`,
    animePath: (id, _season, episode, dub) =>
      `/embed/anime/${id}/${episode}${dub ? "?dub=true" : ""}`
  }),
  defineProvider({
    key: "vidsrc",
    name: "VidSrc",
    category: "other",
    idType: "both",
    website: "https://vidsrc.to",
    referrerPolicy: "no-referrer",
    moviePath: (id) => `/embed/movie/${id}`,
    tvPath: (id, season, episode) => `/embed/tv/${id}/${season}/${episode}`
  }),
  defineProvider({
    key: "vidsrcpro",
    name: "VidSrc Pro",
    category: "other",
    idType: "both",
    website: "https://vidsrc.mov",
    referrerPolicy: "no-referrer",
    moviePath: (id) => `/embed/movie/${id}`,
    tvPath: (id, season, episode) => `/embed/tv/${id}/${season}/${episode}`
  }),
  defineProvider({
    key: "vidup",
    name: "VidUp",
    category: "other",
    idType: "tmdb",
    website: "https://vidup.to",
    referrerPolicy: "no-referrer",
    params: STANDARD_EMBED_PLAYER_PARAMS,
    moviePath: (id) => `/movie/${id}`,
    tvPath: (id, season, episode) => `/tv/${id}/${season}/${episode}`
  }),
  defineProvider({
    key: "vidzee",
    name: "VidZee",
    category: "other",
    idType: "tmdb",
    website: "https://player.vidzee.wtf",
    referrerPolicy: "no-referrer",
    moviePath: (id) => `/embed/movie/${id}`,
    tvPath: (id, season, episode) => `/embed/tv/${id}/${season}/${episode}`
  }),
  defineProvider({
    key: "vidzen",
    name: "VidZen",
    category: "primary",
    idType: "tmdb",
    website: "https://vidzen.fun",
    progress: { controlApi: true },
    referrerPolicy: "no-referrer",
    moviePath: (id) => `/movie/${id}`,
    tvPath: (id, season, episode) => `/tv/${id}/${season}/${episode}`
  }),
  defineProvider({
    key: "vixsrc",
    name: "VixSrc",
    category: "other",
    idType: "tmdb",
    website: "https://vixsrc.to",
    progress: { resumeParam: "startAt" },
    referrerPolicy: "no-referrer",
    params: {
      primaryColor: { type: "hex" },
      secondaryColor: { type: "hex" },
      autoplay: { type: "boolean", default: true },
      startAt: { type: "time" },
      lang: { type: "string" }
    },
    moviePath: (id) => `/movie/${id}`,
    tvPath: (id, season, episode) => `/tv/${id}/${season}/${episode}`
  }),
  defineProvider({
    key: "zxcstream",
    name: "ZXCStream",
    category: "other",
    idType: "tmdb",
    website: "https://zxcstream.xyz",
    referrerPolicy: "no-referrer",
    params: {
      dubLang: { type: "string" },
      server: { type: "string" },
      domainAd: { type: "string" },
      color: { type: "hex" },
      autoplay: { type: "boolean" },
      back: { type: "boolean" }
    },
    moviePath: (id) => `/player/movie/${id}`,
    tvPath: (id, season, episode) => `/player/tv/${id}/${season}/${episode}`
  })
];
