/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvShowsRouteImport } from './routes/tv-shows'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as BestRouteImport } from './routes/best'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'

const TvShowsRoute = TvShowsRouteImport.update({
  id: '/tv-shows',
  path: '/tv-shows',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BestRoute = BestRouteImport.update({
  id: '/best',
  path: '/best',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/best': typeof BestRoute
  '/history': typeof HistoryRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/tv-shows': typeof TvShowsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/best': typeof BestRoute
  '/history': typeof HistoryRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/tv-shows': typeof TvShowsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/best': typeof BestRoute
  '/history': typeof HistoryRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/tv-shows': typeof TvShowsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/best'
    | '/history'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/settings'
    | '/tv-shows'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/best'
    | '/history'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/settings'
    | '/tv-shows'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/watch/$id'
  id:
    | '__root__'
    | '/'
    | '/best'
    | '/history'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/settings'
    | '/tv-shows'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestRoute: typeof BestRoute
  HistoryRoute: typeof HistoryRoute
  MoviesRoute: typeof MoviesRoute
  MyListRoute: typeof MyListRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TvShowsRoute: typeof TvShowsRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv-shows': {
      id: '/tv-shows'
      path: '/tv-shows'
      fullPath: '/tv-shows'
      preLoaderRoute: typeof TvShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best': {
      id: '/best'
      path: '/best'
      fullPath: '/best'
      preLoaderRoute: typeof BestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestRoute: BestRoute,
  HistoryRoute: HistoryRoute,
  MoviesRoute: MoviesRoute,
  MyListRoute: MyListRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TvShowsRoute: TvShowsRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
